#!/usr/bin/env python3
"""从 pairing 表生成 TestPlan YAML（database/runs/*_pair_serial.yaml）。

用法:
  python3 scripts/generate_pair_serial_plans.py
  python3 scripts/generate_pair_serial_plans.py --proto csg
  python3 scripts/generate_pair_serial_plans.py --proto dlt645 --pair-id afn01_init_archive
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

from protocol_tool.compiler.pipeline import compile_protocol
from protocol_tool.ir.nodes import ProtocolIR
from protocol_tool.codecs import create_builtin_registry
from protocol_tool.runtime.engine import BuildEngine, DecodeEngine

from tests.pair_serial_plan_gen import build_pair_serial_plan, dump_plan
from tests.protocol_info import CSG_FIELD_DEFAULTS, DLT645_FIELD_DEFAULTS

REGISTRY = str(_PROJECT_ROOT / "protocol_tool" / "protocols" / "registry.yaml")
COMPILED_DIR = str(_PROJECT_ROOT / "compiled")
OUT_DIR = _PROJECT_ROOT / "database" / "runs"

_PROTO = {
    "csg": ("csg_2016", CSG_FIELD_DEFAULTS, "csg_pair_serial.yaml"),
    "dlt645": ("dlt645_2007", DLT645_FIELD_DEFAULTS, "dlt645_pair_serial.yaml"),
}


def generate(*, proto_key: str, pair_id: str | None = None) -> Path:
    proto_name, defaults_template, filename = _PROTO[proto_key]
    compile_protocol(REGISTRY, proto_name, output_dir=COMPILED_DIR)
    ir = ProtocolIR.from_json_file(f"{COMPILED_DIR}/{proto_name}.ir.json")
    codecs = create_builtin_registry()
    build_engine = BuildEngine(ir, codecs)
    decode_engine = DecodeEngine(ir, codecs)

    plan = build_pair_serial_plan(
        proto_key=proto_key,
        ir=ir,
        build_engine=build_engine,
        decode_engine=decode_engine,
        defaults=dict(defaults_template),
        pair_id=pair_id,
    )
    if pair_id:
        filename = f"{proto_key}_pair_serial_{pair_id}.yaml"

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / filename
    meta = plan.pop("_meta", {})
    header = (
        f"# Generated by scripts/generate_pair_serial_plans.py — do not edit by hand.\n"
        f"# pairs: {meta.get('pair_count', 0)}\n"
        f"# regenerate: python3 scripts/generate_pair_serial_plans.py --proto {proto_key}\n"
    )
    out_path.write_text(header + dump_plan(plan), encoding="utf-8")
    print(f"Wrote {out_path} ({meta.get('pair_count', 0)} pairs)")
    return out_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="生成配对串口 TestPlan YAML")
    parser.add_argument("--proto", choices=["csg", "dlt645", "all"], default="all")
    parser.add_argument("--pair-id", help="仅生成单条 pairing（输出独立文件）")
    args = parser.parse_args(argv)

    protos = ["csg", "dlt645"] if args.proto == "all" else [args.proto]
    for key in protos:
        generate(proto_key=key, pair_id=args.pair_id)
    return 0


if __name__ == "__main__":
    sys.exit(main())
